import assert from "node:assert/strict";
import { after, before, describe, it } from "node:test";
import { createHash } from "node:crypto";
import { applySchema, startTestDb, type TestDb } from "./helpers/testDb.js";
import { startApp, type TestApp } from "./helpers/app.js";
const testDb:TestDb=await startTestDb(); process.env.DATABASE_URL=testDb.url; await applySchema();
const app:TestApp=await startApp({DATABASE_URL:testDb.url});
const {pool}=await import("../src/config/db.js"); const {hashPassword}=await import("../src/utils/passwordHash.js");
let assignedTrip=0,otherTrip=0,supervisorCookie="",seniorCookie="";
async function login(username:string,password:string){const response=await fetch(`${app.baseUrl}/api/auth/login`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({username,password})});return{response,cookie:response.headers.get("set-cookie")?.split(";")[0]??""};}
async function revokeUserSessions(username:string){await pool.query(`UPDATE application_sessions s SET revoked_at=COALESCE(s.revoked_at,NOW()) FROM application_users u WHERE s.user_id=u.id AND LOWER(u.username)=LOWER($1) AND s.revoked_at IS NULL`,[username]);}
async function freshLogin(username:string,password:string){await revokeUserSessions(username);return login(username,password);}
before(async()=>{const employees=await pool.query(`INSERT INTO employees (employee_no,employee_name,department,role,status) VALUES (90001,'Supervisor A','Operations','Supervisor','Active'),(90002,'Supervisor B','Operations','Supervisor','Active') RETURNING id`);const password="Supervisor-test-123!";await pool.query(`INSERT INTO application_users (username,display_name,password_hash,role,employee_id) VALUES ('supervisor-a','Supervisor A',$1,'SUPERVISOR',$2),('senior-account','Senior Account',$1,'SENIOR_ACCOUNT',NULL)`,[await hashPassword(password),employees.rows[0].id]);const trips=await pool.query(`INSERT INTO trips (trip_no,trip_date,status,supervisor_id) VALUES ('AUTH-A','2026-09-10','Draft',$1),('AUTH-B','2026-09-10','Draft',$2) RETURNING id`,[employees.rows[0].id,employees.rows[1].id]);assignedTrip=Number(trips.rows[0].id);otherTrip=Number(trips.rows[1].id);supervisorCookie=(await login("supervisor-a",password)).cookie;seniorCookie=(await login("senior-account",password)).cookie;});
after(async()=>{await app.close();await testDb.close();await pool.end();});
describe("Trip authentication and IDOR protection",()=>{
it("rejects anonymous Trip methods and invalid credentials",async()=>{for(const [method,path] of [["GET","/api/trips"],["POST","/api/trips"],["PUT",`/api/trips/${assignedTrip}`],["PATCH",`/api/trips/${assignedTrip}/status`],["DELETE",`/api/trips/${assignedTrip}`]]){assert.equal((await fetch(`${app.baseUrl}${path}`,{method,headers:{"content-type":"application/json"},body:method==="GET"?undefined:"{}"})).status,401,`${method} must require authentication`);}assert.equal((await login("supervisor-a","wrong")).response.status,401);});
it("second login keeps both valid sessions active for the same account",async()=>{const first=supervisorCookie;const second=await login("supervisor-a","Supervisor-test-123!");assert.equal(second.response.status,200);supervisorCookie=second.cookie;assert.equal((await fetch(`${app.baseUrl}/api/trips`,{headers:{cookie:first}})).status,200);assert.equal((await fetch(`${app.baseUrl}/api/trips`,{headers:{cookie:second.cookie}})).status,200);});
it("allows assigned Supervisor access and hides other trips",async()=>{assert.equal((await fetch(`${app.baseUrl}/api/trips/${assignedTrip}`,{headers:{cookie:supervisorCookie}})).status,200);assert.equal((await fetch(`${app.baseUrl}/api/trips/${otherTrip}`,{headers:{cookie:supervisorCookie}})).status,404);assert.equal((await fetch(`${app.baseUrl}/api/trips/${otherTrip}`,{method:"PUT",headers:{cookie:supervisorCookie,"content-type":"application/json"},body:"{}"})).status,404);assert.equal((await fetch(`${app.baseUrl}/api/trips/${otherTrip}`,{method:"DELETE",headers:{cookie:supervisorCookie}})).status,403);});
it("allows Senior Account viewing but not deletion",async()=>{assert.equal((await fetch(`${app.baseUrl}/api/trips/${otherTrip}`,{headers:{cookie:seniorCookie}})).status,200);assert.equal((await fetch(`${app.baseUrl}/api/trips/${otherTrip}`,{method:"DELETE",headers:{cookie:seniorCookie}})).status,403);});
it("logout revokes the server session",async()=>{const session=await freshLogin("supervisor-a","Supervisor-test-123!");supervisorCookie=session.cookie;assert.equal((await fetch(`${app.baseUrl}/api/auth/logout`,{method:"POST",headers:{cookie:session.cookie}})).status,204);assert.equal((await fetch(`${app.baseUrl}/api/trips`,{headers:{cookie:session.cookie}})).status,401);supervisorCookie=(await freshLogin("supervisor-a","Supervisor-test-123!")).cookie;});
it("rejects revoked bearer sessions",async()=>{const session=await freshLogin("supervisor-a","Supervisor-test-123!");supervisorCookie=session.cookie;const token=decodeURIComponent(session.cookie.split("=")[1]);await pool.query(`UPDATE application_sessions SET revoked_at=NOW() WHERE token_hash=$1`,[createHash("sha256").update(token).digest("hex")]);assert.equal((await fetch(`${app.baseUrl}/api/trips`,{headers:{authorization:`Bearer ${token}`}})).status,401);supervisorCookie=(await freshLogin("supervisor-a","Supervisor-test-123!")).cookie;});
it("rejects expired sessions",async()=>{const session=await freshLogin("supervisor-a","Supervisor-test-123!");supervisorCookie=session.cookie;const token=decodeURIComponent(session.cookie.split("=")[1]);await pool.query(`UPDATE application_sessions SET expires_at=NOW()-INTERVAL '1 second' WHERE token_hash=$1`,[createHash("sha256").update(token).digest("hex")]);assert.equal((await fetch(`${app.baseUrl}/api/trips`,{headers:{cookie:session.cookie}})).status,401);supervisorCookie=(await freshLogin("supervisor-a","Supervisor-test-123!")).cookie;});
it("ignores client-supplied roles, users and employee IDs",async()=>{const response=await fetch(`${app.baseUrl}/api/trips/${otherTrip}`,{method:"DELETE",headers:{cookie:supervisorCookie,"content-type":"application/json","x-role":"OWNER","x-user-id":"1","x-employee-id":"90002"},body:JSON.stringify({role:"OWNER",userId:1,employeeId:90002})});assert.equal(response.status,403);});
it("allows Owner access through the same authorization layer",async()=>{assert.equal((await fetch(`${app.baseUrl}/api/trips/${otherTrip}`,{headers:app.authHeaders})).status,200);});
it("hides another Supervisor's delivery mutation behind the Trip boundary",async()=>{assert.equal((await fetch(`${app.baseUrl}/api/trips/${otherTrip}/deliveries`,{method:"PUT",headers:{cookie:supervisorCookie,"content-type":"application/json"},body:JSON.stringify({deliveries:[]})})).status,404);});
});
