import type { BoxDetail, DieselEntry, ShopDelivery, Trip, TripStatus, TripStepStatuses, TripSummary } from "../types/models.js";
import { type PaginationParams, type PaginatedResult } from "../utils/pagination.js";
import { type TripWizardStep } from "../utils/tripResume.js";
export declare const tripsService: {
    list(filters?: {
        fromDate?: string;
        toDate?: string;
        status?: string;
        vehicleId?: number;
        supervisorId?: number;
        search?: string;
        includeDeleted?: boolean;
        pagination?: PaginationParams | null;
        full?: boolean;
    }): Promise<TripSummary[] | Trip[] | PaginatedResult<TripSummary>>;
    /**
     * Trip List â€” returns ONLY completed/approved, non-deleted trips.
     * The eligibility rule lives in the SQL WHERE clause (see buildTripListWhere),
     * so the frontend can never pull Draft/Pending/Deleted rows and filter locally.
     */
    listCompleted(filters?: {
        fromDate?: string;
        toDate?: string;
        vehicleId?: number;
        supervisorId?: number;
        driverId?: number;
        farmId?: number;
        search?: string;
        pagination?: PaginationParams | null;
    }): Promise<TripSummary[] | PaginatedResult<TripSummary>>;
    /**
     * Trip List detail â€” full trip only when eligible (completed + not deleted).
     * A Draft / Pending / Deleted trip id returns 404, so the read-only view can
     * never surface a trip that should not be in the list.
     */
    getCompletedById(id: number): Promise<{
        resumeStep: TripWizardStep | null;
        resumeStepLabel: string | null;
        wizardProgress: import("../utils/tripResume.js").WizardProgress;
        id: number;
        tripNo: string;
        tripDate: string;
        status: TripStatus;
        startTime: string | null;
        vehicleId: number | null;
        vehicleNo: string | null;
        driverId: number | null;
        driverName: string | null;
        supervisorId: number | null;
        supervisorName: string | null;
        helpers: string[];
        loaders: string[];
        openingMeter: number | null;
        advanceAmount: number;
        startStepSubmitted: boolean;
        startStepSubmittedAt: string | null;
        sourceFarmId: number | null;
        sourceFarm: string | null;
        reachedTime: string | null;
        destMeter: number | null;
        pickupTolls: number;
        farmAddress?: string | null;
        avgBirdWeight?: number | null;
        farmRemarks?: string | null;
        farmBirdTypeId?: number | null;
        farmBirdType?: string | null;
        farmBirdCount?: number | null;
        farmLoadWeight?: number | null;
        farmRate?: number | null;
        farmAmount?: number | null;
        farmStepSubmitted: boolean;
        farmStepSubmittedAt: string | null;
        dcWeight: number;
        totalBirds: number;
        boxes: number;
        avgWeight: number;
        pickupLoadTime: string | null;
        boxDetails: BoxDetail[];
        dcPhotoKey?: string | null;
        pickupStepSubmitted: boolean;
        pickupStepSubmittedAt: string | null;
        deliveries: ShopDelivery[];
        deliveryStepSubmitted: boolean;
        deliveriesStepSubmittedAt: string | null;
        closingMeter: number | null;
        endMeter?: number | null;
        endTime: string | null;
        deliveryTolls: number;
        destinationTolls?: number;
        meals?: number;
        loading?: number;
        mealsTiffin?: number;
        vehicleMaintenance?: number;
        othersRC?: number;
        others1Amt?: number;
        others2Amt?: number;
        others3Amt?: number;
        others4Amt?: number;
        others5Amt?: number;
        dieselEntries?: DieselEntry[];
        fuel: number;
        expense: number;
        driverBata?: number;
        helperBata?: number;
        totalTripExpense?: number;
        remarks: string;
        submittedAt?: string | null;
        endStepSubmitted: boolean;
        expensesStepSubmitted: boolean;
        expensesStepSubmittedAt: string | null;
        totalKm: number;
        totalShops: number;
        totalWeight: number;
        totalDeliveredWeight: number;
        totalBirdsDelivered: number;
        totalMortality: number;
        totalMortalityCount: number;
        totalMortalityWeight: number;
        weightLoss: number;
        survivalRate: number;
        lastShop: string | null;
        rateCompleted: boolean;
        deleted: boolean;
        deletedReason?: string | null;
        approvedBy?: string | null;
        approvedAt?: string | null;
        rejectedBy?: string | null;
        rejectedAt?: string | null;
        rejectedReason?: string | null;
        createdAt?: string | null;
        updatedAt?: string | null;
        stepStatuses?: TripStepStatuses;
        dcPhotoData?: string | null;
        dcPhotoMime?: string | null;
    }>;
    getById(id: number): Promise<{
        resumeStep: TripWizardStep | null;
        resumeStepLabel: string | null;
        wizardProgress: import("../utils/tripResume.js").WizardProgress;
        stepStatuses: TripStepStatuses;
        id: number;
        tripNo: string;
        tripDate: string;
        status: TripStatus;
        startTime: string | null;
        vehicleId: number | null;
        vehicleNo: string | null;
        driverId: number | null;
        driverName: string | null;
        supervisorId: number | null;
        supervisorName: string | null;
        helpers: string[];
        loaders: string[];
        openingMeter: number | null;
        advanceAmount: number;
        startStepSubmitted: boolean;
        startStepSubmittedAt: string | null;
        sourceFarmId: number | null;
        sourceFarm: string | null;
        reachedTime: string | null;
        destMeter: number | null;
        pickupTolls: number;
        farmAddress?: string | null;
        avgBirdWeight?: number | null;
        farmRemarks?: string | null;
        farmBirdTypeId?: number | null;
        farmBirdType?: string | null;
        farmBirdCount?: number | null;
        farmLoadWeight?: number | null;
        farmRate?: number | null;
        farmAmount?: number | null;
        farmStepSubmitted: boolean;
        farmStepSubmittedAt: string | null;
        dcWeight: number;
        totalBirds: number;
        boxes: number;
        avgWeight: number;
        pickupLoadTime: string | null;
        boxDetails: BoxDetail[];
        dcPhotoKey?: string | null;
        pickupStepSubmitted: boolean;
        pickupStepSubmittedAt: string | null;
        deliveries: ShopDelivery[];
        deliveryStepSubmitted: boolean;
        deliveriesStepSubmittedAt: string | null;
        closingMeter: number | null;
        endMeter?: number | null;
        endTime: string | null;
        deliveryTolls: number;
        destinationTolls?: number;
        meals?: number;
        loading?: number;
        mealsTiffin?: number;
        vehicleMaintenance?: number;
        othersRC?: number;
        others1Amt?: number;
        others2Amt?: number;
        others3Amt?: number;
        others4Amt?: number;
        others5Amt?: number;
        dieselEntries?: DieselEntry[];
        fuel: number;
        expense: number;
        driverBata?: number;
        helperBata?: number;
        totalTripExpense?: number;
        remarks: string;
        submittedAt?: string | null;
        endStepSubmitted: boolean;
        expensesStepSubmitted: boolean;
        expensesStepSubmittedAt: string | null;
        totalKm: number;
        totalShops: number;
        totalWeight: number;
        totalDeliveredWeight: number;
        totalBirdsDelivered: number;
        totalMortality: number;
        totalMortalityCount: number;
        totalMortalityWeight: number;
        weightLoss: number;
        survivalRate: number;
        lastShop: string | null;
        rateCompleted: boolean;
        deleted: boolean;
        deletedReason?: string | null;
        approvedBy?: string | null;
        approvedAt?: string | null;
        rejectedBy?: string | null;
        rejectedAt?: string | null;
        rejectedReason?: string | null;
        createdAt?: string | null;
        updatedAt?: string | null;
        dcPhotoData?: string | null;
        dcPhotoMime?: string | null;
    }>;
    createDraft(body?: Partial<Trip>): Promise<{
        resumeStep: TripWizardStep;
        resumeStepLabel: string;
        wizardProgress: import("../utils/tripResume.js").WizardProgress;
        stepStatuses: TripStepStatuses;
        id: number;
        tripNo: string;
        tripDate: string;
        status: TripStatus;
        startTime: string | null;
        vehicleId: number | null;
        vehicleNo: string | null;
        driverId: number | null;
        driverName: string | null;
        supervisorId: number | null;
        supervisorName: string | null;
        helpers: string[];
        loaders: string[];
        openingMeter: number | null;
        advanceAmount: number;
        startStepSubmitted: boolean;
        startStepSubmittedAt: string | null;
        sourceFarmId: number | null;
        sourceFarm: string | null;
        reachedTime: string | null;
        destMeter: number | null;
        pickupTolls: number;
        farmAddress?: string | null;
        avgBirdWeight?: number | null;
        farmRemarks?: string | null;
        farmBirdTypeId?: number | null;
        farmBirdType?: string | null;
        farmBirdCount?: number | null;
        farmLoadWeight?: number | null;
        farmRate?: number | null;
        farmAmount?: number | null;
        farmStepSubmitted: boolean;
        farmStepSubmittedAt: string | null;
        dcWeight: number;
        totalBirds: number;
        boxes: number;
        avgWeight: number;
        pickupLoadTime: string | null;
        boxDetails: BoxDetail[];
        dcPhotoKey?: string | null;
        pickupStepSubmitted: boolean;
        pickupStepSubmittedAt: string | null;
        deliveries: ShopDelivery[];
        deliveryStepSubmitted: boolean;
        deliveriesStepSubmittedAt: string | null;
        closingMeter: number | null;
        endMeter?: number | null;
        endTime: string | null;
        deliveryTolls: number;
        destinationTolls?: number;
        meals?: number;
        loading?: number;
        mealsTiffin?: number;
        vehicleMaintenance?: number;
        othersRC?: number;
        others1Amt?: number;
        others2Amt?: number;
        others3Amt?: number;
        others4Amt?: number;
        others5Amt?: number;
        dieselEntries?: DieselEntry[];
        fuel: number;
        expense: number;
        driverBata?: number;
        helperBata?: number;
        totalTripExpense?: number;
        remarks: string;
        submittedAt?: string | null;
        endStepSubmitted: boolean;
        expensesStepSubmitted: boolean;
        expensesStepSubmittedAt: string | null;
        totalKm: number;
        totalShops: number;
        totalWeight: number;
        totalDeliveredWeight: number;
        totalBirdsDelivered: number;
        totalMortality: number;
        totalMortalityCount: number;
        totalMortalityWeight: number;
        weightLoss: number;
        survivalRate: number;
        lastShop: string | null;
        rateCompleted: boolean;
        deleted: boolean;
        deletedReason?: string | null;
        approvedBy?: string | null;
        approvedAt?: string | null;
        rejectedBy?: string | null;
        rejectedAt?: string | null;
        rejectedReason?: string | null;
        createdAt?: string | null;
        updatedAt?: string | null;
        dcPhotoData?: string | null;
        dcPhotoMime?: string | null;
    }>;
    /** Autosave engine â€” partial upsert with optimistic locking */
    save(id: number | null, body: Partial<Trip> & Record<string, unknown>): Promise<{
        resumeStep: TripWizardStep | null;
        resumeStepLabel: string | null;
        wizardProgress: import("../utils/tripResume.js").WizardProgress;
        stepStatuses: TripStepStatuses;
        id: number;
        tripNo: string;
        tripDate: string;
        status: TripStatus;
        startTime: string | null;
        vehicleId: number | null;
        vehicleNo: string | null;
        driverId: number | null;
        driverName: string | null;
        supervisorId: number | null;
        supervisorName: string | null;
        helpers: string[];
        loaders: string[];
        openingMeter: number | null;
        advanceAmount: number;
        startStepSubmitted: boolean;
        startStepSubmittedAt: string | null;
        sourceFarmId: number | null;
        sourceFarm: string | null;
        reachedTime: string | null;
        destMeter: number | null;
        pickupTolls: number;
        farmAddress?: string | null;
        avgBirdWeight?: number | null;
        farmRemarks?: string | null;
        farmBirdTypeId?: number | null;
        farmBirdType?: string | null;
        farmBirdCount?: number | null;
        farmLoadWeight?: number | null;
        farmRate?: number | null;
        farmAmount?: number | null;
        farmStepSubmitted: boolean;
        farmStepSubmittedAt: string | null;
        dcWeight: number;
        totalBirds: number;
        boxes: number;
        avgWeight: number;
        pickupLoadTime: string | null;
        boxDetails: BoxDetail[];
        dcPhotoKey?: string | null;
        pickupStepSubmitted: boolean;
        pickupStepSubmittedAt: string | null;
        deliveries: ShopDelivery[];
        deliveryStepSubmitted: boolean;
        deliveriesStepSubmittedAt: string | null;
        closingMeter: number | null;
        endMeter?: number | null;
        endTime: string | null;
        deliveryTolls: number;
        destinationTolls?: number;
        meals?: number;
        loading?: number;
        mealsTiffin?: number;
        vehicleMaintenance?: number;
        othersRC?: number;
        others1Amt?: number;
        others2Amt?: number;
        others3Amt?: number;
        others4Amt?: number;
        others5Amt?: number;
        dieselEntries?: DieselEntry[];
        fuel: number;
        expense: number;
        driverBata?: number;
        helperBata?: number;
        totalTripExpense?: number;
        remarks: string;
        submittedAt?: string | null;
        endStepSubmitted: boolean;
        expensesStepSubmitted: boolean;
        expensesStepSubmittedAt: string | null;
        totalKm: number;
        totalShops: number;
        totalWeight: number;
        totalDeliveredWeight: number;
        totalBirdsDelivered: number;
        totalMortality: number;
        totalMortalityCount: number;
        totalMortalityWeight: number;
        weightLoss: number;
        survivalRate: number;
        lastShop: string | null;
        rateCompleted: boolean;
        deleted: boolean;
        deletedReason?: string | null;
        approvedBy?: string | null;
        approvedAt?: string | null;
        rejectedBy?: string | null;
        rejectedAt?: string | null;
        rejectedReason?: string | null;
        createdAt?: string | null;
        updatedAt?: string | null;
        dcPhotoData?: string | null;
        dcPhotoMime?: string | null;
    }>;
    submitStep(id: number, step: TripWizardStep, body: Partial<Trip> & Record<string, unknown>): Promise<{
        resumeStep: TripWizardStep | null;
        resumeStepLabel: string | null;
        wizardProgress: import("../utils/tripResume.js").WizardProgress;
        stepStatuses: TripStepStatuses;
        id: number;
        tripNo: string;
        tripDate: string;
        status: TripStatus;
        startTime: string | null;
        vehicleId: number | null;
        vehicleNo: string | null;
        driverId: number | null;
        driverName: string | null;
        supervisorId: number | null;
        supervisorName: string | null;
        helpers: string[];
        loaders: string[];
        openingMeter: number | null;
        advanceAmount: number;
        startStepSubmitted: boolean;
        startStepSubmittedAt: string | null;
        sourceFarmId: number | null;
        sourceFarm: string | null;
        reachedTime: string | null;
        destMeter: number | null;
        pickupTolls: number;
        farmAddress?: string | null;
        avgBirdWeight?: number | null;
        farmRemarks?: string | null;
        farmBirdTypeId?: number | null;
        farmBirdType?: string | null;
        farmBirdCount?: number | null;
        farmLoadWeight?: number | null;
        farmRate?: number | null;
        farmAmount?: number | null;
        farmStepSubmitted: boolean;
        farmStepSubmittedAt: string | null;
        dcWeight: number;
        totalBirds: number;
        boxes: number;
        avgWeight: number;
        pickupLoadTime: string | null;
        boxDetails: BoxDetail[];
        dcPhotoKey?: string | null;
        pickupStepSubmitted: boolean;
        pickupStepSubmittedAt: string | null;
        deliveries: ShopDelivery[];
        deliveryStepSubmitted: boolean;
        deliveriesStepSubmittedAt: string | null;
        closingMeter: number | null;
        endMeter?: number | null;
        endTime: string | null;
        deliveryTolls: number;
        destinationTolls?: number;
        meals?: number;
        loading?: number;
        mealsTiffin?: number;
        vehicleMaintenance?: number;
        othersRC?: number;
        others1Amt?: number;
        others2Amt?: number;
        others3Amt?: number;
        others4Amt?: number;
        others5Amt?: number;
        dieselEntries?: DieselEntry[];
        fuel: number;
        expense: number;
        driverBata?: number;
        helperBata?: number;
        totalTripExpense?: number;
        remarks: string;
        submittedAt?: string | null;
        endStepSubmitted: boolean;
        expensesStepSubmitted: boolean;
        expensesStepSubmittedAt: string | null;
        totalKm: number;
        totalShops: number;
        totalWeight: number;
        totalDeliveredWeight: number;
        totalBirdsDelivered: number;
        totalMortality: number;
        totalMortalityCount: number;
        totalMortalityWeight: number;
        weightLoss: number;
        survivalRate: number;
        lastShop: string | null;
        rateCompleted: boolean;
        deleted: boolean;
        deletedReason?: string | null;
        approvedBy?: string | null;
        approvedAt?: string | null;
        rejectedBy?: string | null;
        rejectedAt?: string | null;
        rejectedReason?: string | null;
        createdAt?: string | null;
        updatedAt?: string | null;
        dcPhotoData?: string | null;
        dcPhotoMime?: string | null;
    }>;
    softDelete(id: number, reason?: string): Promise<{
        id: number;
        deleted: boolean;
    }>;
    updateStatus(id: number, body: {
        status: string;
        approvedBy?: string;
        rejectedBy?: string;
        rejectedReason?: string;
        reason?: string;
    }): Promise<{
        id: number;
        tripNo: string;
        tripDate: string;
        status: TripStatus;
        startTime: string | null;
        vehicleId: number | null;
        vehicleNo: string | null;
        driverId: number | null;
        driverName: string | null;
        supervisorId: number | null;
        supervisorName: string | null;
        helpers: string[];
        loaders: string[];
        openingMeter: number | null;
        advanceAmount: number;
        startStepSubmitted: boolean;
        startStepSubmittedAt: string | null;
        sourceFarmId: number | null;
        sourceFarm: string | null;
        reachedTime: string | null;
        destMeter: number | null;
        pickupTolls: number;
        farmAddress?: string | null;
        avgBirdWeight?: number | null;
        farmRemarks?: string | null;
        farmBirdTypeId?: number | null;
        farmBirdType?: string | null;
        farmBirdCount?: number | null;
        farmLoadWeight?: number | null;
        farmRate?: number | null;
        farmAmount?: number | null;
        farmStepSubmitted: boolean;
        farmStepSubmittedAt: string | null;
        dcWeight: number;
        totalBirds: number;
        boxes: number;
        avgWeight: number;
        pickupLoadTime: string | null;
        boxDetails: BoxDetail[];
        dcPhotoKey?: string | null;
        pickupStepSubmitted: boolean;
        pickupStepSubmittedAt: string | null;
        deliveries: ShopDelivery[];
        deliveryStepSubmitted: boolean;
        deliveriesStepSubmittedAt: string | null;
        closingMeter: number | null;
        endMeter?: number | null;
        endTime: string | null;
        deliveryTolls: number;
        destinationTolls?: number;
        meals?: number;
        loading?: number;
        mealsTiffin?: number;
        vehicleMaintenance?: number;
        othersRC?: number;
        others1Amt?: number;
        others2Amt?: number;
        others3Amt?: number;
        others4Amt?: number;
        others5Amt?: number;
        dieselEntries?: DieselEntry[];
        fuel: number;
        expense: number;
        driverBata?: number;
        helperBata?: number;
        totalTripExpense?: number;
        remarks: string;
        submittedAt?: string | null;
        endStepSubmitted: boolean;
        expensesStepSubmitted: boolean;
        expensesStepSubmittedAt: string | null;
        totalKm: number;
        totalShops: number;
        totalWeight: number;
        totalDeliveredWeight: number;
        totalBirdsDelivered: number;
        totalMortality: number;
        totalMortalityCount: number;
        totalMortalityWeight: number;
        weightLoss: number;
        survivalRate: number;
        lastShop: string | null;
        rateCompleted: boolean;
        deleted: boolean;
        deletedReason?: string | null;
        approvedBy?: string | null;
        approvedAt?: string | null;
        rejectedBy?: string | null;
        rejectedAt?: string | null;
        rejectedReason?: string | null;
        createdAt?: string | null;
        updatedAt?: string | null;
        stepStatuses?: TripStepStatuses;
        dcPhotoData?: string | null;
        dcPhotoMime?: string | null;
    }>;
    /** Backs GET /trips/vehicle/:vehicleId/last-meter â€” the Trip Step 1 opening
     * meter hint. Upgraded to the universal cross-module latest (trips + fuel +
     * maintenance), not just trip closing meters, while keeping the same
     * response shape the frontend already consumes. */
    lastClosingMeter(vehicleId: number): Promise<{
        closingMeter: number;
        source: import("../utils/vehicleMeterLedger.js").MeterSourceType;
        ref: string;
        tripNo: string | null;
        tripDate: string;
    } | null>;
};
