import type { Trip } from "../../../../shared/trip/types";

/**
 * Compatibility facade for existing Desktop Trip imports.
 * Shared calculations and validation are authoritative for Desktop + Mobile.
 */
export {
  calculateAvgWeight,
  calculateTripKPIs,
  calculateTotals,
  calculatePickupTotals,
  calculateDeliveryMetrics,
  applyDeliveryMetrics,
  calculateDeliveryDisplayTotals,
  calculateKM,
  calculateTripDistances,
  sumFlattenedDieselLitres,
} from "../../../../shared/trip/calculations";
export {
  validateStartStep,
  validateFarmStep,
  validatePickupStep,
  validateDeliveriesStep,
  validateEndStep,
  validateFinalTrip,
  validateTrip,
} from "../../../../shared/trip/validation";

// Legacy browser-only numbering remains here for old Trip List/Delete flows.
// Permanent Trip numbers continue to be generated by PostgreSQL/backend.
export function generateTripNo(existingTrips: Trip[], date: string): string {
  const dateStr = date.replace(/-/g, "");
  const count = existingTrips.filter((trip) => trip.tripDate === date).length + 1;
  if (count > 999) return `TRP-${dateStr}-${Date.now().toString().slice(-4)}`;
  return `TRP-${dateStr}-${String(count).padStart(3, "0")}`;
}

export function renumberPendingTripsForDate(date: string): Trip[] {
  const allTrips: Trip[] = JSON.parse(localStorage.getItem("vehicleTrips") || "[]");
  const dateStr = date.replace(/-/g, "");
  const pendingTrips = allTrips
    .filter((trip) => trip.tripDate === date && trip.status === "Pending")
    .sort((a, b) => {
      const aNumber = parseInt(a.tripNo.split("-")[2] || "0", 10);
      const bNumber = parseInt(b.tripNo.split("-")[2] || "0", 10);
      return aNumber - bNumber;
    });
  pendingTrips.forEach((trip, index) => {
    trip.tripNo = `TRP-${dateStr}-${String(index + 1).padStart(3, "0")}`;
  });
  localStorage.setItem("vehicleTrips", JSON.stringify(allTrips));
  return allTrips;
}

export function canEditTrip(createdAt: string): boolean {
  const differenceDays = Math.floor(
    (Date.now() - new Date(createdAt).getTime()) / (1000 * 60 * 60 * 24)
  );
  return differenceDays <= 10;
}

export function canDeleteTrip(createdAt: string): boolean {
  return canEditTrip(createdAt);
}

export function isTripCompleted(status: "Pending" | "Completed"): boolean {
  return status === "Completed";
}

export function isTripPending(status: "Pending" | "Completed"): boolean {
  return status === "Pending";
}
