ALTER TABLE fuel_expenses
  ADD COLUMN IF NOT EXISTS gps_lat NUMERIC(10, 7),
  ADD COLUMN IF NOT EXISTS gps_lon NUMERIC(10, 7),
  ADD COLUMN IF NOT EXISTS gps_accuracy NUMERIC(10, 2),
  ADD COLUMN IF NOT EXISTS gps_captured_at TIMESTAMPTZ;
